# Generated by Django 4.2.30 on 2026-06-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
