# Generated by Django 4.2.30 on 2026-06-23 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_alter_produit_image_principale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_création', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.panier')),
                ('variante_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.variante_produit')),
            ],
            options={
                'unique_together': {('panier', 'variante_produit')},
            },
        ),
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ManyToManyField(through='projet.PanierProduit', to='projet.variante_produit'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
    ]
