# Generated by Django 4.2.30 on 2026-07-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_order_orderitem_order_projet_orde_created_402a18_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100)),
                ('description_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='projet.categorie'),
        ),
    ]
