# Generated by Django 4.2.30 on 2026-07-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_categorie_remove_produit_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom_categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom_categorie',
            new_name='categorie',
        ),
    ]
