# Generated by Django 4.2.30 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_rename_nom_categorie_categorie_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
