# Generated by Django 4.2.30 on 2026-07-11 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_categorie_image_principale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entier', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
                ('stripe_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='projet_orde_created_402a18_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='date_commande',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantité',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='strip_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='montant_payé',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='nom_entier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.produit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variante_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.variante_produit'),
        ),
        migrations.AddField(
            model_name='adressecommande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_commande', to=settings.AUTH_USER_MODEL),
        ),
    ]
