# Generated by Django 4.2.30 on 2026-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0008_adressecommande_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressecommande',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
