# Generated by Django 4.2.30 on 2026-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0009_alter_adressecommande_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_globale',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_secondaire',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
