# Generated by Django 4.2.30 on 2026-08-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0010_produit_image_globale_produit_image_secondaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='envoyé',
        ),
    ]
