# Generated by Django 4.2.30 on 2026-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0011_rename_status_order_envoyé'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_envoie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
