# Generated by Django 4.2.30 on 2026-10-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0012_order_date_envoie'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payé',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projet.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projet.produit'),
        ),
    ]
